# Generated by Django 5.2.7 on 2025-10-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Page', '0002_profile_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='profile_pic/profile-1.jpg', upload_to='profile_pic/'),
        ),
    ]
