# Generated by Django 5.2.7 on 2025-11-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Page', '0004_alter_profile_profile_pic_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(blank=True),
        ),
    ]
