# Generated by Django 5.2.7 on 2025-11-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Page', '0005_alter_post_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='profile_pic/myown.jpg', upload_to='profile_pic'),
        ),
    ]
