# Generated by Django 5.2.7 on 2025-11-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Page', '0007_alter_profile_profile_pic_friendrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10),
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='accepted',
        ),
    ]
