"""
Django settings for Friend project.
Generated by 'django-admin startproject' using Django 5.2.7.
"""

import os
import dj_database_url
from pathlib import Path

# ============================
# BASE DIRECTORY
# ============================
# Correct BASE_DIR should be 2 parents above (not 3)
BASE_DIR = Path(__file__).resolve().parent.parent


# ============================
# SECURITY SETTINGS
# ============================
SECRET_KEY = os.environ.get("SECRET_KEY", "dev-secret-key")

# Automatically turn off DEBUG on Render
DEBUG = os.environ.get("RENDER", False) != "true"

ALLOWED_HOSTS = ['*']  # Render uses dynamic hosts


# ============================
# INSTALLED APPS
# ============================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Page',
]


# ============================
# MIDDLEWARE
# ============================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',

    # Whitenoise must come right after SecurityMiddleware
    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ============================
# URL + WSGI
# ============================
ROOT_URLCONF = 'Friend.urls'
WSGI_APPLICATION = 'Friend.wsgi.application'


# ============================
# TEMPLATES
# ============================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# ============================
# DATABASE CONFIG
# ============================
# Default (local) database: SQLite
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# If Render provides DATABASE_URL, overwrite with PostgreSQL
DATABASE_URL = os.environ.get("DATABASE_URL")
if DATABASE_URL:
    DATABASES['default'] = dj_database_url.config(
        default=DATABASE_URL,
        conn_max_age=600,
        ssl_require=True
    )


# ============================
# PASSWORD VALIDATION
# ============================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ============================
# INTERNATIONALIZATION
# ============================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ============================
# STATIC FILES
# ============================
STATIC_URL = '/static/'

# Where collectstatic puts files
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Your development/static folder
STATICFILES_DIRS = [BASE_DIR / "static"]

# Whitenoise storage
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# ============================
# MEDIA FILES
# ============================
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ============================
# LOGIN URL
# ============================
LOGIN_URL = '/log_in/'


# ============================
# DEFAULT PRIMARY KEY FIELD
# ============================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
